apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-deployment
spec:
  replicas: 3
# select the templete which matches the declared label. 
  selector:
    matchLabels:
      server: app
  template:
    metadata:
      labels:
        server: app
    spec:
      containers:
        - name: app
          image: app:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production





