apiVersion: apps/v1
kind: Deployment 

metadata:
  name: nginx-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      server: nginx
  template:
    metadata:
      labels:
        server: nginx
    spec:
      containers:
        - name: nginx
          image: server:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

    