apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  labels:
    name: cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: app:latest
              name: cronjob
              imagePullPolicy: Never
              command: ["echo", "My first Cron job in Kubernetes"]
          restartPolicy: Never
