apiVersion: apps/v1
kind: Deployment

metadata:
  name: init-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      server: init
  template:
    metadata:
      labels:
        server: init
    spec:
      volumes:
        - name: shared-volume
          emptyDir: {}
      initContainers:
        - name: busybox
          image: busybox:latest
          volumeMounts:
            - name: shared-volume
              mountPath: /nginx-data
          args:
            - /bin/sh
            - -c
            - echo '<h1>Hello Kubernetes!</h1>' > /nginx-data/index.html

      containers:
        - name: init
          image: server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/share/nginx/html

      # nodeSelector:
      #   demoserver: "true"
