apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-deamonset
  labels:
    deamon-name: ngin-deamon

spec:
  selector:
    matchLabels:
      deamon: nginx
  template:
    metadata:
      labels:
        deamon: nginx
    spec:
      containers:
        - name: deamonnginx
          image: server:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
      terminationGracePeriodSeconds: 30
