apiVersion: v1 
kind: Service 

metadata:
  name: {{.Values.nginx.name}}-loadnlancer

spec:
  selector:
    server: {{.Values.nginx.name}} 
  ports:
    - port: {{.Values.nginx.image.containerPort}}
      targetPort: {{.Values.nginx.image.containerPort}}
  type: LoadBalancer