apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "buming the docker image to the latest one"
  name: nodejs-project

spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 6
  strategy:
    #   type: Recreate
    type: Recreate
  minReadySeconds: 5
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs-prod
          image: server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
