apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim

spec:
  storageClassName: local-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
