# DOCS_LINK : https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/

# object restrictions to a namespace
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: quota-examples
#   namespace: demo
# spec:
#   hard:
#     pods: 10
#     configmaps: "1"

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: demo
spec:
  hard:
    #   maximum that a single resource can ask for!
    requests.cpu: "1"
    requests.memory: 1Gi
    # upper limit (collectivly all the pods or defined resources)
    limits.cpu: "2"
    limits.memory: 2Gi
#  Adding reoureces to you pods or objects is very important
# user spec.container[*].resouces
# resources:
#   requests:
#     memory: "100Mi"
#   limits:
#     memory: "200Mi"

# LIMIT RANGES
# apiVersion: v1
# kind: LimitRange
# metadata:
#   name: cpu-min-max-demo-lr
# spec:
#   limits:
#   - max:
#       cpu: "800m"
#     min:
#       cpu: "200m"
#     type: Container
