apiVersion: v1
kind: Secret

metadata:
  name: secret-example

type: Opaque
data:
  USER_NAME: QWtpcmEgU2FtYQ==
  PASSWORD: c2FtYWhzYWRoZmhhZGpzZmhramFkZmthamRmaA==
  LOCATION: VG9reW8=
immutable: false
